name: Build and Publish

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build Jar
        run: ./gradlew build '-Pversion=${{ github.run_number }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DFRPC
          path: ./build/libs/DFRPC*.jar
      - name: Publish Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ github.run_number }}"
          prerelease: false
          files: |
            ./build/libs/
      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: QmAnYs7W
          name: "DiamondFire RPC v${{ github.run_number }}"
          version: "v${{ github.run_number }}"
          changelog: "${{ github.event.head_commit.message }}"
          dependencies: |-
            [{
              "project_id": "P7dR8mSH",
              "dependency_type": "required"
            }, {
              "project_id": "dBv9so2c",
              "dependency_type": "required"      
            }, {
              "project_id": "ccKDOlHs",
              "dependency_type": "required"
            }, {
              "project_id": "mOgUt4GM",
              "dependency_type": "required"
            }]
          loaders: |-
            fabric
          game-versions: |-
            1.21.3
          files: '["./build/libs/DFRPC-${{ github.run_number }}.jar", "./build/libs/DFRPC-${{ github.run_number }}-sources.jar"]'
          primary-file: "DFRPC-${{ github.run_number }}.jar"